ARDUINO_DIR  = /opt/arduino
AVRDUDE=/usr/bin/avrdude

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB1

ARDUINO_LIBS = OneWire XBee SoftwareSerial

AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf

include /usr/share/arduino/Arduino.mk

